hash-format = "sha256"

[[files]]
file = "mods/antighost.pw.toml"
hash = "59f11097c3005d5efcec93d0cd8a1ce690dc1ed65b9e56c2b1ed7bdca24cf022"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "e256b55ec94408fd32ba3963fb21cd54718a087134ed24ea2c4c660f25bae977"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "54c92a1d353ca55a4ecb8d21c4b1fdb8f354b434a0c9448b523237cec9de1d7a"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "5d790c79d579bbebbc3cb5c9656cd1b3b361a18b364492821585a42ee07f652c"
metafile = true

[[files]]
file = "mods/beenfo.pw.toml"
hash = "75950d95a5b439f64dc046394013429a04544907cb482079663ffb52374b6f07"
metafile = true

[[files]]
file = "mods/borderless-mining.pw.toml"
hash = "5cc5a514cc9b8567abda1d5860a8ac3afdf868906caf9bd24c6c534943e1fb4c"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "9fb071407761cdb22323713a3f24ca27f04bb67c0ea455ee2e73778c6ecece75"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "b8df5a6ae8c4f2c5492a9235463aa3f231af27964d7e240fcba1421c99e89736"
metafile = true

[[files]]
file = "mods/clickthrough.pw.toml"
hash = "896caf86ddf75501e5634614e700e1feffcf1a3a2cb1234200a5eb62f99b39b5"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "f250d6778f5b8d03ca32913bea5ea677508e9bb6d8201cdebe005bbe9c3100ee"
metafile = true

[[files]]
file = "mods/continue.pw.toml"
hash = "129f7b6a59e75f5a0356c19c6a326d0aa93beed8e8caa142f79971ae9f8e71c0"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ab1c014ce67654e89af779137bdfd1f6f22888af218f44cf5d83e943d0d5fbc4"
metafile = true

[[files]]
file = "mods/deathlog.pw.toml"
hash = "4bf0a9827aec78e4c94fe3889bfe97449ca2107751bfdf6b1203749c30c76c3f"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "60d43521b68e4639ad7e258a8d10759e70a22e543aa0050727283a848466d0b9"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "6ea1eddd8ff08bd26c296bf6c1e3906c0e2ec5ad0b334a0adca4f1f2a1bb03cc"
metafile = true

[[files]]
file = "mods/eating-animation.pw.toml"
hash = "13baf86c7202df729de43ea5ac8766581c39e35651391d080a9a2a33252c2996"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "179d1b7ca85bd3202749e2cc95413daec331dd37dbcf66d07f12a2cd1c0ee397"
metafile = true

[[files]]
file = "mods/emuno.pw.toml"
hash = "8f0c18360533351fff9237b803b1a91fb86cc9b00d56e61f116076e654c9f8e8"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "d8141ee9ad948865c4da8594fe1e785ff6933d3f5b299234d002e2014559c0e4"
metafile = true

[[files]]
file = "mods/exordium.pw.toml"
hash = "350e3aa46726c4ce33c9c383c673ab131c76c9015b5aa8c5532521beed1dfca4"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "5d6ea0cebb49bd66b8ff5262809f5b73725c3a5881606a291ded2cc2372de95a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "a856296531bab559c7dbe061827078e206b9cf194be3be618c462c62ab4fd841"
metafile = true

[[files]]
file = "mods/fabrictailor.pw.toml"
hash = "fff92f1ff0c8a99cacbddf6b7e667886b0df51856a7b6be07958f1771de8afd6"
metafile = true

[[files]]
file = "mods/fastquit.pw.toml"
hash = "ff278c8a9a5e56d412fb2e7106790b0ac33b0a4a8699978f0ae4d5a2c70c63b3"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "4146027b92b4885fddec00435233c61c3728b5e09265982ab187021519a4fa89"
metafile = true

[[files]]
file = "mods/fix-keyboard-on-linux.pw.toml"
hash = "6e572f70d25f8f509761cb13f0d29eb2f9333713e4d32b33ecd576f7545a738e"
metafile = true

[[files]]
file = "mods/hold-that-chunk.pw.toml"
hash = "88d504ca7157466de1a296c456a95e20412bf14bec48e606499fe3319a9ddbab"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "b411b04e1dace15c7fc1465bb161c8e621750b1577282e0918f956212a57e864"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "e416b18eebf514dea2014cf5c7fd3ee8493934a0b4e937509f15172ad271fde2"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "7169f560465ba70f204d3c4189cf3d1faef8ae6cf3dc063733a4d53f612a4d94"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "919e0f9bdf11b4960591cef1f0cb7fe6bb8bbf21135b423c0d014b00b4a06cb8"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "fe6abe1ea33393fe1441801f79eda74ea892e5f4b677a56eccafafcbf4d253ca"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "d398662ae6e9d87e89384ba50a9787dbeb9425902a18b0cd8239efd0b966b453"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "037f6b72bde7b586901f261820197efb52a369cdad3557eeaaa7a3f8e9c19799"
metafile = true

[[files]]
file = "mods/lazydfu.pw.toml"
hash = "b4ca05b39b85c27cd97ccb65d5fb832f5e9fd7ee5710542a3e69dfa30a97ea7d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "3dedde5213176d72e1c353877fa44315945e8f3da2ba05f5679d81e9f558bb1d"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "3c0945a312aca06a2185b00cb03ae482949b008d72614497148aa2df301af019"
metafile = true

[[files]]
file = "mods/moddetectionpreventer.pw.toml"
hash = "d5b31676ddcb673733e322e0e3b15894924ab6136a28b3573462b2307b6fd56b"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b88658496a83e1ade03fe955191c379d413db8915f2f8d9641797b6f22865b25"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "b61b0ccdc8328d637c0f57cbb25258491b94ae03c89c4194ad6ca8b86579dd28"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "1447b2cbf7c1d96fd410f85fdd029c1de4a4f8709d09146e602b6054065e49c0"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "ef9c4bc27256d065df4feaba2bc05883ba22987c41cd48786070d37ae85cc8e1"
metafile = true

[[files]]
file = "mods/mouse-wheelie.pw.toml"
hash = "4c1fed6a8d4681c1e00d93786ec775bede5a77317bcf70df92cee9908d8d6891"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "a045df0a5d03ef89d92ca9318aa42a5a5e7617b37dd38d32b0a7058c0f6f4ef7"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "a2a38850af0076bcfb2c34327f59626d73a87876d03c4039092babfc673428c6"
metafile = true

[[files]]
file = "mods/nvidium.pw.toml"
hash = "07dd8775324c01058896b4572e23a1ca1c355186cc501c61fc68e1151c5e177c"
metafile = true

[[files]]
file = "mods/open-loader.pw.toml"
hash = "c263e847df8e8deea386ddcab450f6936247a6b580ae07026f8f58e09062d1aa"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "f3636b986e4bf3fd2c66e393dca81170247b157b076f02160ff755e17dc792a9"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "975478c93b1218131fd48695cd7efb9bbe0d69125409940b015a7058e42fb6be"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "bab65e32078216683b5b01cf60d06cd01a3cd4ff1339d1b4de1091338c3b1e21"
metafile = true

[[files]]
file = "mods/rrls.pw.toml"
hash = "937bd200c74fe8c5391a4c85b9e901ed35332c00b3757a82df545c14770a585a"
metafile = true

[[files]]
file = "mods/screenshot-to-clipboard.pw.toml"
hash = "672f3809a2053eef01aea4015ca4b0d4be6c507622172c091c17833b8d2ffb39"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "f7c09e537f9db67804dd7df6b8ba3a0cfb63429ad992a99e8f8faba33187ded2"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "5e73967368d47038c38dc52fa298b45603fbe6baf2608f171638ff767178ad9a"
metafile = true

[[files]]
file = "mods/starlight.pw.toml"
hash = "18ee61062b3f43fd026ee620bb2de6073de791132c5067d262bd424628bed4a5"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "44593cfab255a73ae00161802962950525bad36716eb00afda5f3e9bc6f4cba9"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "7dfbf79bf874dcfdb27e4bbc92da56cdab2ffdbee459dfd2eee5a57dacb59ed2"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "c34d19bc94ba7a7fe25727f387f64c6365182f3706d8d313c2d54119bb8b26d6"
metafile = true

[[files]]
file = "mods/world-host.pw.toml"
hash = "eab5a30d30ab3837e16512c2b4e3831458ddec1aedd040501a23a70ebf8ab71a"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "0e64714c116db266b1c35b0fea980d0ad75ddee7639d13f89d5cedf6c7e336e7"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "7005e926a32cfe6e1191ea0da9f65635e28f9dec4d827044c43da622697ba9c2"
metafile = true

[[files]]
file = "resourcepacks/translations-for-sodium.pw.toml"
hash = "a3a62ad561358f43670434ced35740bc901e0eac9502815d4253041cfbfba113"
metafile = true
